package com.example.ui

object GameStrings {
    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["uz"]?.get(key) ?: key
    }

    private val translations = mapOf(
        "uz" to mapOf(
            "app_title" to "Zulmat Shartnomasi",
            "start_game" to "OʻYINNI BOSHLASH",
            "codex_lore" to "OKULT KODEKS & AI",
            "settings" to "SOZLAMALAR",
            "day_phase" to "KUNDUZGI FAZA",
            "night_phase" to "TUNGI BOSQIN",
            "day_hours" to "Kunduz: 06:00 — 18:00",
            "night_hours" to "Tun: 18:00 — 06:00",
            "scavenge" to "Ekspeditsiya",
            "necro_bank" to "Oliy Zom: Soya Banki",
            "engineering" to "Blood Con Muhandislik",
            "bio_pod" to "Bio-Growth Pod",
            "radio_occult" to "Radio-Okultizm",
            "liquid_blood" to "Suyuq Qon",
            "dark_ether" to "Qora Eter",
            "raw_biomass" to "Biomassa",
            "iron_pipes" to "Quvurlar",
            "ammo" to "Oʻq-dori",
            "sanity" to "Aql-idrok",
            "base_hp" to "Baza Holati",
            "debt" to "Oliy Zom Qarzi",
            "start_night" to "TUNNI BOSHLASH ➔",
            "shoot" to "OTISH",
            "reload" to "QUROQNI OʻQLASH",
            "ritual_circle" to "Safran Tilsimi (25 Efir)",
            "ether_flare" to "Efir Mashʻalasi (Sanity)",
            "turrets_online" to "Blood Con Turretlari Faol",
            "eye_pledged_warning" to "Diqqat: Koʻz garovda! Koʻrish doirasi toraygan.",
            "arm_pledged_warning" to "Diqqat: Qoʻl garovda! Otish tezligi sekinlashgan.",
            "take_loan" to "Kredit Olish",
            "repay_loan" to "Qarzni Yopish",
            "pledge_collateral" to "Aʻzoni Garovga Qoʻyish",
            "pledge_eye" to "Chap Koʻzni Garovga Qoʻyish",
            "pledge_arm" to "Oʻng Qoʻlni Garovga Qoʻyish",
            "pledge_soul" to "Ruhni Garovga Qoʻyish (Sanity)",
            "grow_organ" to "Aʻzo Oʻstirishni Boshlash (80 Biomassa + 100 Qon)",
            "pod_growing" to "Organ oʻsmoqda...",
            "tune_frequency" to "Chastotani Sozlash",
            "ask_codex" to "Grimoirega Savol Berish (Google Search Grounding)",
            "grounding_powered" to "Gemini 3.5 Flash & Search Grounding orqali faollashtirilgan",
            "night_survived" to "TUN MUVAFFAQIYATLI OʻTTI!",
            "base_fallen" to "BAZA VAYRON BOʻLDI!",
            "continue_day" to "Yangi Kunga Oʻtish ➔"
        ),
        "en" to mapOf(
            "app_title" to "Contract of Darkness",
            "start_game" to "START GAME",
            "codex_lore" to "OCCULT CODEX & AI",
            "settings" to "SETTINGS",
            "day_phase" to "DAY PHASE",
            "night_phase" to "NIGHT INVASION",
            "day_hours" to "Day: 06:00 — 18:00",
            "night_hours" to "Night: 18:00 — 06:00",
            "scavenge" to "Scavenge Expedition",
            "necro_bank" to "Oliy Zom: Necro-Bank",
            "engineering" to "Blood Con Engineering",
            "bio_pod" to "Bio-Growth Pod",
            "radio_occult" to "Occult Radio",
            "liquid_blood" to "Liquid Blood",
            "dark_ether" to "Dark Ether",
            "raw_biomass" to "Raw Biomass",
            "iron_pipes" to "Iron Pipes",
            "ammo" to "Ammunition",
            "sanity" to "Sanity",
            "base_hp" to "Base Integrity",
            "debt" to "Oliy Zom Debt",
            "start_night" to "ENTER NIGHTFALL ➔",
            "shoot" to "FIRE SHOTGUN",
            "reload" to "RELOAD",
            "ritual_circle" to "Saffron Circle (25 Ether)",
            "ether_flare" to "Ether Flare (Sanity)",
            "turrets_online" to "Blood Con Turrets Active",
            "eye_pledged_warning" to "Warning: Eye is pledged! Peripheral vision restricted.",
            "arm_pledged_warning" to "Warning: Arm is pledged! Reload and handling degraded.",
            "take_loan" to "Request Loan",
            "repay_loan" to "Settle Debt",
            "pledge_collateral" to "Pledge Flesh as Collateral",
            "pledge_eye" to "Pledge Left Eye",
            "pledge_arm" to "Pledge Right Arm",
            "pledge_soul" to "Pledge Soul (Sanity Leech)",
            "grow_organ" to "Regenerate Organ (80 Biomass + 100 Blood)",
            "pod_growing" to "Incubating organ tissue...",
            "tune_frequency" to "Tune Occult Frequency",
            "ask_codex" to "Consult Ancient Codex (Google Search Grounding)",
            "grounding_powered" to "Powered by Gemini 3.5 Flash with Google Search Grounding",
            "night_survived" to "NIGHT SURVIVED!",
            "base_fallen" to "BASE OVERRUN!",
            "continue_day" to "Greet the Dawn ➔"
        ),
        "ru" to mapOf(
            "app_title" to "Договор Тьмы",
            "start_game" to "НАЧАТЬ ИГРУ",
            "codex_lore" to "ОККУЛЬТНЫЙ КОДЕКС & ИИ",
            "settings" to "НАСТРОЙКИ",
            "day_phase" to "ДНЕВНАЯ ФАЗА",
            "night_phase" to "НОЧНОЙ ПРОРЫВ",
            "day_hours" to "День: 06:00 — 18:00",
            "night_hours" to "Ночь: 18:00 — 06:00",
            "scavenge" to "Экспедиция за ресурсами",
            "necro_bank" to "Олий Зом: Некро-Банк",
            "engineering" to "Инженерия Blood Con",
            "bio_pod" to "Био-Капсула Выращивания",
            "radio_occult" to "Оккультное Радио",
            "liquid_blood" to "Жидкая Кровь",
            "dark_ether" to "Темный Эфир",
            "raw_biomass" to "Биомасса",
            "iron_pipes" to "Трубы",
            "ammo" to "Боеприпасы",
            "sanity" to "Рассудок",
            "base_hp" to "Прочность Базы",
            "debt" to "Долг Олий Зому",
            "start_night" to "НАЧАТЬ НОЧЬ ➔",
            "shoot" to "ВЫСТРЕЛ",
            "reload" to "ПЕРЕЗАРЯДКА",
            "ritual_circle" to "Шафрановый круг (25 Эфира)",
            "ether_flare" to "Эфирная вспышка (Рассудок)",
            "turrets_online" to "Турели Blood Con активны",
            "eye_pledged_warning" to "Внимание: Глаз в залоге! Обзор сужен.",
            "arm_pledged_warning" to "Внимание: Рука в залоге! Скорость стрельбы снижена.",
            "take_loan" to "Взять кредит",
            "repay_loan" to "Выплатить долг",
            "pledge_collateral" to "Заложить органы",
            "pledge_eye" to "Заложить левый глаз",
            "pledge_arm" to "Заложить правую руку",
            "pledge_soul" to "Заложить душу (Утечка рассудка)",
            "grow_organ" to "Вырастить орган (80 Биомассы + 100 Крови)",
            "pod_growing" to "Орган формируется...",
            "tune_frequency" to "Настройка частоты",
            "ask_codex" to "Спросить Кодекс (Поиск с заземлением Google)",
            "grounding_powered" to "Работает на Gemini 3.5 Flash с Google Search Grounding",
            "night_survived" to "НОЧЬ ПЕРЕЖИТА!",
            "base_fallen" to "БАЗА ПАЛА!",
            "continue_day" to "Встретить рассвет ➔"
        ),
        "tr" to mapOf(
            "app_title" to "Karanlık Sözleşmesi",
            "start_game" to "OYUNA BAŞLA",
            "codex_lore" to "OKÜLT KODEKS & YAPAY ZEKA",
            "settings" to "AYARLAR",
            "day_phase" to "GÜNDÜZ EVRESİ",
            "night_phase" to "GECE BASKINI",
            "scavenge" to "Keşif ve Yağma",
            "necro_bank" to "Oliy Zom: Gölge Bankası",
            "engineering" to "Blood Con Mühendisliği",
            "bio_pod" to "Biyo-Büyüme Kapsülü",
            "radio_occult" to "Okült Radyo",
            "liquid_blood" to "Sıvı Kan",
            "dark_ether" to "Karanlık Eter",
            "raw_biomass" to "Biyokütle",
            "iron_pipes" to "Demir Borular",
            "ammo" to "Mühimmat",
            "sanity" to "Akıl Sağlığı",
            "base_hp" to "Üs Durumu",
            "debt" to "Oliy Zom Borcu",
            "start_night" to "GECEYE GEÇ ➔",
            "shoot" to "ATEŞ ET",
            "reload" to "DOLDUR",
            "ritual_circle" to "Safran Tılsımı (25 Eter)",
            "ether_flare" to "Eter Meşalesi",
            "take_loan" to "Kredi Al",
            "repay_loan" to "Borcu Öde",
            "grow_organ" to "Organ Büyütmeyi Başlat",
            "tune_frequency" to "Frekansı Ayarla",
            "ask_codex" to "Kodekse Sor (Google Search Grounding)",
            "grounding_powered" to "Gemini 3.5 Flash & Google Search Destekli",
            "night_survived" to "GECE ATLATILDI!",
            "base_fallen" to "ÜS DÜŞTÜ!",
            "continue_day" to "Şafağa Ulaş ➔"
        )
    )
}
